apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: accuknox-multi-cluster-helper
  name: accuknox-multi-cluster-helper
spec:
  template:
    spec:
      serviceAccountName: accuknox-multi-cluster-helper
      containers:
        - name: accuknox-multi-cluster-helper
          image: bitnami/kubectl:1.31
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_NAME_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: accuknox-multi-cluster-helper
                  key: clusterNamePrefix
            - name: GENERATED_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: accuknox-multi-cluster-helper
                  key: generatedClusterName
          command: ["/bin/sh", "-c"]
          args:
            - |
              if [ -n "$CLUSTER_NAME_PREFIX" ] && [ -z "$GENERATED_CLUSTER_NAME" ]; then
                NEW_VALUE="$CLUSTER_NAME_PREFIX-$(date +%Y%m%d%H%M%S)"
                printf "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: accuknox-multi-cluster-helper\n  namespace: $NAMESPACE\ndata:\n  generatedClusterName: \"%s\"" "$NEW_VALUE" | kubectl apply -f -

                kubectl patch configmap onboarding-vars -n $NAMESPACE --type='json' -p='[{"op": "replace", "path": "/data/CLUSTER_NAME", "value": $CLUSTER_NAME_PREFIX}]'
                kubectl patch configmap onboarding-vars -n $NAMESPACE --type='json' -p='[{"op": "replace", "path": "/data/cluster_name", "value": $CLUSTER_NAME_PREFIX}]'

                kubectl rollout restart deployment agents-operator -n $NAMESPACE
                kubectl rollout restart deployment policy-enforcement-agent -n $NAMESPACE
                kubectl rollout restart deployment feeder-service -n $NAMESPACE
                kubectl rollout restart deployment shared-informer-agent -n $NAMESPACE
              fi
              # sleep infinity
      restartPolicy: Never
