apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cm.yaml
  - job.yaml
  - role-binding.yaml
  - role.yaml
  - sa.yaml

patches:
- patch: |-
    apiVersion: v1
    data:
      clusterNamePrefix: "anthos-testing-multi"                         # cluster name prefix
    kind: ConfigMap
    metadata:
      name: accuknox-multi-cluster-helper

namespace: agents # should be same as accuknox-agents