apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: accuknox-multi-cluster-helper
  name: accuknox-multi-cluster-helper
subjects:
  - kind: ServiceAccount
    name:  accuknox-multi-cluster-helper
roleRef:
  kind: Role
  name:  accuknox-multi-cluster-helper
  apiGroup: rbac.authorization.k8s.io