apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: accuknox-multi-cluster-helper
  name: accuknox-multi-cluster-helper
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["accuknox-multi-cluster-helper", "onboarding-vars"] 
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["agents-operator", "policy-enforcement-agent", "feeder-service", "shared-informer-agent"] 
    verbs: ["get", "patch"]