apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: accuknox-multi-cluster-helper
  name: accuknox-multi-cluster-helper
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]