---
# Source: kubearmor-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubearmor-operator
  namespace: kubearmor
---
# Source: kubearmor-operator/templates/clusterrole-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-operator-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  - configmaps
  verbs:
  - get
  - create
  - delete
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - list
  - get
  - create
  - delete
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - batch
  verbs:
  - create
  resources:
  - jobs
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - create
  - get
- apiGroups:
  - operator.kubearmor.com
  resources:
  - kubearmorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kubearmor.com
  resources:
  - kubearmorconfigs/status
  verbs:
  - get
  - patch
  - update  
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
---
# Source: kubearmor-operator/templates/clusterrole-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-operator-manage-kubearmor-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  - configmaps
  verbs:
  - get
  - patch
  - list
  - watch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - get
  - patch
  - list
  - watch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - patch
  - list
  - watch
  - update
- apiGroups:
  - security.kubearmor.com
  resources:
  - kubearmorpolicies
  - kubearmorclusterpolicies
  - kubearmorhostpolicies
  verbs:
  - get
  - list
  - watch
  - update
  - delete
- nonResourceURLs:
  - /apis
  - /apis/*
  verbs:
  - get
---
# Source: kubearmor-operator/templates/clusterrole-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmor-operator-manage-controller-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - create
  - delete
  - get
  - patch
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: 
  - get 
  - list 
  - watch
- apiGroups:
  - security.kubearmor.com
  resources:
  - kubearmorpolicies
  - kubearmorclusterpolicies
  - kubearmorhostpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.kubearmor.com
  resources:
  - kubearmorpolicies/status
  - kubearmorclusterpolicies/status
  - kubearmorhostpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
# Source: kubearmor-operator/templates/clusterrole-binding-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubearmor-operator-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubearmor-operator-clusterrole
subjects:
- kind: ServiceAccount
  name: kubearmor-operator
  namespace: kubearmor
---
# Source: kubearmor-operator/templates/clusterrole-binding-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubearmor-operator-manage-kubearmor-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubearmor-operator-manage-kubearmor-clusterrole
subjects:
- kind: ServiceAccount
  name: kubearmor-operator
  namespace: kubearmor
---
# Source: kubearmor-operator/templates/clusterrole-binding-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubearmor-operator-manage-controller-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubearmor-operator-manage-controller-clusterrole
subjects:
- kind: ServiceAccount
  name: kubearmor-operator
  namespace: kubearmor
---
# Source: kubearmor-operator/templates/clusterrole-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubearmor-operator-tls-secrets-role
  namespace: kubearmor
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - update
  - delete
  resourceNames:
  - kubearmor-ca
  - kubearmor-client-certs
  - kubearmor-relay-server-certs
  - kubearmor-controller-webhook-server-cert
# cannot restric create by resource name, https://kubernetes.io/docs/reference/access-authn-authz/rbac/  
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
---
# Source: kubearmor-operator/templates/clusterrole-binding-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubearmor-operator-tls-secrets-rolebinding
  namespace: kubearmor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubearmor-operator-tls-secrets-role
subjects:
- kind: ServiceAccount
  name: kubearmor-operator
  namespace: kubearmor
---
# Source: kubearmor-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-operator
  namespace: kubearmor
  labels:
    kubearmor-app: kubearmor-operator
spec:
  selector:
    matchLabels:
      kubearmor-app: kubearmor-operator
  template:
    metadata:
      labels:
        kubearmor-app: kubearmor-operator
    spec:
      containers:
      - name: kubearmor-operator
        env:
        - name: KUBEARMOR_OPERATOR_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: kubearmor/kubearmor-operator:stable
        imagePullPolicy: Always

      serviceAccountName: kubearmor-operator

