apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
subjects:
  - kind: ServiceAccount
    name:  {{ template "fullname" . }}
roleRef:
  kind: Role
  name:  {{ template "fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}