apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: kubearmor-operator
    repo: https://kubearmor.github.io/charts
    version: v1.4.1
    releaseName: kubearmor-operator
    namespace: kubearmor
  - name: agents
    repo: oci://registry-1.docker.io/accuknox/accuknox-agents
    version: v0.6.7
    releaseName: agents
    namespace: agents
    valuesFile: values.yaml