apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-tls
  labels: {{- toYaml .Values.commonLabels | nindent 4 }}
    app: {{ template "fullname" . }}
type: Opaque
data:
  certificate.crt: {{ .Values.ssl.certificate }}
  private.key: {{ .Values.ssl.key }}