apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - policy.yaml

namespace: default

commonAnnotations:
  config.kubernetes.io/depends-on: apps/namespaces/kubearmor/Deployment/kubearmor-operator