apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels: {{- toYaml .Values.commonLabels | nindent 4 }}
    app: {{ template "fullname" . }}
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: {{ template "fullname" . }}