apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agents # should not be same as accuknox agent

helmGlobals:
  chartHome: ./local-charts
helmCharts:
- name: amc-helper
  releaseName: amc-helper
  valuesFile: ./value_overrides.yaml