apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutating-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutating-webhook
  template:
    metadata:
      labels:
        app: mutating-webhook
    spec:
      containers:
      - name: mutating-webhook
        image: safeeraccuknox/demo:accuknox-multi-cluster-setup-helper-9eb33ae
        imagePullPolicy: Always
        ports:
        - containerPort: 5000