apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: accuknox-multi-cluster-helper-webhook
webhooks:
- name: accuknox-multi-cluster-helper-webhook.agents.svc
  matchPolicy: Equivalent
  admissionReviewVersions: ["v1"]
  sideEffects: None
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["configmaps"]
    scope: "Namespaced"
  failurePolicy: Fail
  timeoutSeconds: 20
  clientConfig:
    # intended for demonstration purposes only and should be regarded as insecure.
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJRERUQ0NBZlVDQVFBd2VqRUxNQWtHQTFVRUJoTUNRVlV4RGpBTUJnTlZCQWdNQlZOMFlYUmxNUTB3Q3dZRApWUVFIREFSRGFYUjVNUkV3RHdZRFZRUUtEQWhCWTJOMWEyNXZlREU1TURjR0ExVUVBd3d3WVdOamRXdHViM2d0CmJYVnNkR2t0WTJ4MWMzUmxjaTFvWld4d1pYSXRkMlZpYUc5dmF5NWhaMlZ1ZEhNdWMzWmpNSUlCSWpBTkJna3EKaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE3bkVkYWhwTUpjay9LQjRnWkdIZFJ5am9TaWo4NDEwTwpGY0U2cEVqSmp1aXhYYVExem5CbE1PRDRBZ2FOZThscTgrNjFjTGRlVjZkTXRpTFN1em91SWRUTFNIcVh4Y084CktlS0VhakJEZUJWblhrTTA4OWkweCtPZDV1ZmhQT1lEa2R2SUMyU0xMUzVUQUpZdE1maUhDSjNvaHFGWlpZVXEKZnhUSlVhdGFwVGZiTXdvbzVpeWNFNm9wVk9QclAzUUF6cFNLM3podGdVRVJKaUJTeHlMa1FscEYwMG8za1lLZApMUWtpaWhFeGJmNVR2ZXRRSlQyTVZBb3RPT1dnWG42UWR6eHdrU3U4NGRUd0poMGsxOXhhZ1Q1VjFNcWNYSkV2Cnh1eWEyeHF3TTJRZi9nTzNmRXl1NXNXQm1IOGxxWHBmaE9kL0RUZGkvTFlBazJyQkRnbG1Hd0lEQVFBQm9FNHcKVEFZSktvWklodmNOQVFrT01UOHdQVEE3QmdOVkhSRUVOREF5Z2pCaFkyTjFhMjV2ZUMxdGRXeDBhUzFqYkhWegpkR1Z5TFdobGJIQmxjaTEzWldKb2IyOXJMbUZuWlc1MGN5NXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCCkFJVStuaEFQOGF4VWZKNUdhTzB0bXBQa3pHMEF4RHVyTjlkNkZrODNCN0k4THNoSGZUNTQ3NkZRZkVHSDRrUlIKZms4aTQ0azBRa0lxZEYrQXFsODdPR3QxazlUMmNxK3A1Z3NXYVdXQmlVWlg1bGFadDJITW91YnU4WXZxc1RBTAppWlhYQWorMFVsS2JQS3AxQUZKWk56eXRhS3JmTWdPUllVdmg1WVNWdDViVmdkZUQyQWQ2ZDJnN0pDOC9IK2poCitCN1lmRjg4ckpBaGdsNkJjVnFDWHlORHJKTVlFa0FoWm1JcUF0VksxTGoyRXMvSWp1bWJUOGcvOW1JODB4ekMKTWhqaWFSOFR5YVBrZHRhVkwyeGNoMnNLUVRYRW1mMGNlVk1nb0daOXkwNzhzQUhwRXJNdk9MOGR6R1l5WmZqaApveTkraUZmaWt3V3JFeXpXdFpYWFMrST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
    service:
      namespace: agents
      name: accuknox-multi-cluster-helper-webhook
      path: /mutate
      port: 5000