name: "Build and Push to Docker Hub"
on:
  push:
    branches:
      - main
    paths:
      - 'accuknox/multi-cluster-setup-helper.v2/*'
jobs:
  build:
    name: "Build and Push to  Docker Hub"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build, tag
        id: build-image
        env:
          REPOSITORY: unixnomad/test
        run: |
          IMAGE_TAG=accuknox-multi-cluster-setup-helper
          docker build -t $REPOSITORY:$IMAGE_TAG .
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "image=$REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"

        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push image to Docker hub
        env:
          IMAGE_NAME: ${{ steps.build-image.outputs.image }}
        id: push-image
        run: |
          docker push $IMAGE_NAME
